#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

appDir=`find "../1_MyBuild" -name "*.app" -print`
find "$appDir/Contents/Plugins" -name '*.meta' -print -delete

chmod -R a+xr "$appDir"

echo "+------------------------------------------------------------------+"
echo "|           Delete all meta files in app/plugins folder.           |"
echo "+------------------------------------------------------------------+"
echo " "
echo "DONE! All meta files deleted @ $appDir/Contents/Plugins "
echo " "

exit 0 